// Dados estáticos para versões da Bíblia
export const BIBLE_VERSIONS = [
    { abbrev: 'almeida', name: { 'pt-BR': 'João Ferreira de Almeida', 'en': 'João Ferreira de Almeida' } },
    { abbrev: 'kjv', name: { 'pt-BR': 'King James Version', 'en': 'King James Version' } },
    { abbrev: 'web', name: { 'pt-BR': 'World English Bible', 'en': 'World English Bible' } }
];

// Dados estáticos para os livros da Bíblia
export const allBooks = [
    { "abbrev": { "pt": "gn", "en": "gn" }, "author": "Moisés", "chapters": 50, "group": "Pentateuco", "name": { "pt-BR": "Gênesis", "en": "Genesis" }, "testament": "VT" },
    { "abbrev": { "pt": "ex", "en": "ex" }, "author": "Moisés", "chapters": 40, "group": "Pentateuco", "name": { "pt-BR": "Êxodo", "en": "Exodus" }, "testament": "VT" },
    { "abbrev": { "pt": "lv", "en": "lv" }, "author": "Moisés", "chapters": 27, "group": "Pentateuco", "name": { "pt-BR": "Levítico", "en": "Leviticus" }, "testament": "VT" },
    { "abbrev": { "pt": "nm", "en": "nm" }, "author": "Moisés", "chapters": 36, "group": "Pentateuco", "name": { "pt-BR": "Números", "en": "Numbers" }, "testament": "VT" },
    { "abbrev": { "pt": "dt", "en": "dt" }, "author": "Moisés", "chapters": 34, "group": "Pentateuco", "name": { "pt-BR": "Deuteronômio", "en": "Deuteronomy" }, "testament": "VT" },
    { "abbrev": { "pt": "js", "en": "js" }, "author": "Josué", "chapters": 24, "group": "Livros Históricos", "name": { "pt-BR": "Josué", "en": "Joshua" }, "testament": "VT" },
    { "abbrev": { "pt": "jz", "en": "jz" }, "author": "Samuel", "chapters": 21, "group": "Livros Históricos", "name": { "pt-BR": "Juízes", "en": "Judges" }, "testament": "VT" },
    { "abbrev": { "pt": "rt", "en": "rt" }, "author": "Samuel", "chapters": 4, "group": "Livros Históricos", "name": { "pt-BR": "Rute", "en": "Ruth" }, "testament": "VT" },
    { "abbrev": { "pt": "1sm", "en": "1sm" }, "author": "Samuel, Gade e Natã", "chapters": 31, "group": "Livros Históricos", "name": { "pt-BR": "1º Samuel", "en": "1 Samuel" }, "testament": "VT" },
    { "abbrev": { "pt": "2sm", "en": "2sm" }, "author": "Samuel, Gade e Natã", "chapters": 24, "group": "Livros Históricos", "name": { "pt-BR": "2º Samuel", "en": "2 Samuel" }, "testament": "VT" },
    { "abbrev": { "pt": "1rs", "en": "1rs" }, "author": "Jeremias", "chapters": 22, "group": "Livros Históricos", "name": { "pt-BR": "1º Reis", "en": "1 Kings" }, "testament": "VT" },
    { "abbrev": { "pt": "2rs", "en": "2rs" }, "author": "Jeremias", "chapters": 25, "group": "Livros Históricos", "name": { "pt-BR": "2º Reis", "en": "2 Kings" }, "testament": "VT" },
    { "abbrev": { "pt": "1cr", "en": "1cr" }, "author": "Esdras", "chapters": 29, "group": "Livros Históricos", "name": { "pt-BR": "1º Crônicas", "en": "1 Chronicles" }, "testament": "VT" },
    { "abbrev": { "pt": "2cr", "en": "2cr" }, "author": "Esdras", "chapters": 36, "group": "Livros Históricos", "name": { "pt-BR": "2º Crônicas", "en": "2 Chronicles" }, "testament": "VT" },
    { "abbrev": { "pt": "ed", "en": "ed" }, "author": "Esdras", "chapters": 10, "group": "Livros Históricos", "name": { "pt-BR": "Esdras", "en": "Ezra" }, "testament": "VT" },
    { "abbrev": { "pt": "ne", "en": "ne" }, "author": "Neemias", "chapters": 13, "group": "Livros Históricos", "name": { "pt-BR": "Neemias", "en": "Nehemiah" }, "testament": "VT" },
    { "abbrev": { "pt": "et", "en": "et" }, "author": "Mardoqueu", "chapters": 10, "group": "Livros Históricos", "name": { "pt-BR": "Ester", "en": "Esther" }, "testament": "VT" },
    { "abbrev": { "pt": "job", "en": "job" }, "author": "Jó", "chapters": 42, "group": "Livros Poéticos", "name": { "pt-BR": "Jó", "en": "Job" }, "testament": "VT" },
    { "abbrev": { "pt": "sl", "en": "sl" }, "author": "Davi, Salomão, Moisés, Asafe", "chapters": 150, "group": "Livros Poéticos", "name": { "pt-BR": "Salmos", "en": "Psalms" }, "testament": "VT" },
    { "abbrev": { "pt": "pv", "en": "pv" }, "author": "Salomão", "chapters": 31, "group": "Livros Poéticos", "name": { "pt-BR": "Provérbios", "en": "Proverbs" }, "testament": "VT" },
    { "abbrev": { "pt": "ec", "en": "ec" }, "author": "Salomão", "chapters": 12, "group": "Livros Poéticos", "name": { "pt-BR": "Eclesiastes", "en": "Ecclesiastes" }, "testament": "VT" },
    { "abbrev": { "pt": "ct", "en": "ct" }, "author": "Salomão", "chapters": 8, "group": "Livros Poéticos", "name": { "pt-BR": "Cânticos", "en": "Song of Solomon" }, "testament": "VT" },
    { "abbrev": { "pt": "is", "en": "is" }, "author": "Isaías", "chapters": 66, "group": "Profetas Maiores", "name": { "pt-BR": "Isaías", "en": "Isaiah" }, "testament": "VT" },
    { "abbrev": { "pt": "jr", "en": "jr" }, "author": "Jeremias", "chapters": 52, "group": "Profetas Maiores", "name": { "pt-BR": "Jeremias", "en": "Jeremiah" }, "testament": "VT" },
    { "abbrev": { "pt": "lm", "en": "lm" }, "author": "Jeremias", "chapters": 5, "group": "Profetas Maiores", "name": { "pt-BR": "Lamentações de Jeremias", "en": "Lamentations" }, "testament": "VT" },
    { "abbrev": { "pt": "ez", "en": "ez" }, "author": "Ezequiel", "chapters": 48, "group": "Profetas Maiores", "name": { "pt-BR": "Ezequiel", "en": "Ezekiel" }, "testament": "VT" },
    { "abbrev": { "pt": "dn", "en": "dn" }, "author": "Daniel", "chapters": 12, "group": "Profetas Maiores", "name": { "pt-BR": "Daniel", "en": "Daniel" }, "testament": "VT" },
    { "abbrev": { "pt": "os", "en": "os" }, "author": "Oséias", "chapters": 14, "group": "Profetas Menores", "name": { "pt-BR": "Oséias", "en": "Hosea" }, "testament": "VT" },
    { "abbrev": { "pt": "jl", "en": "jl" }, "author": "Joel", "chapters": 3, "group": "Profetas Menores", "name": { "pt-BR": "Joel", "en": "Joel" }, "testament": "VT" },
    { "abbrev": { "pt": "am", "en": "am" }, "author": "Amós", "chapters": 9, "group": "Profetas Menores", "name": { "pt-BR": "Amós", "en": "Amos" }, "testament": "VT" },
    { "abbrev": { "pt": "ob", "en": "ob" }, "author": "Obadias", "chapters": 1, "group": "Profetas Menores", "name": { "pt-BR": "Obadias", "en": "Obadiah" }, "testament": "VT" },
    { "abbrev": { "pt": "jn", "en": "jn" }, "author": "Jonas", "chapters": 4, "group": "Profetas Menores", "name": { "pt-BR": "Jonas", "en": "Jonah" }, "testament": "VT" },
    { "abbrev": { "pt": "mq", "en": "mq" }, "author": "Miquéias", "chapters": 7, "group": "Profetas Menores", "name": { "pt-BR": "Miquéias", "en": "Micah" }, "testament": "VT" },
    { "abbrev": { "pt": "na", "en": "na" }, "author": "Naum", "chapters": 3, "group": "Profetas Menores", "name": { "pt-BR": "Naum", "en": "Nahum" }, "testament": "VT" },
    { "abbrev": { "pt": "hc", "en": "hc" }, "author": "Habacuque", "chapters": 3, "group": "Profetas Menores", "name": { "pt-BR": "Habacuque", "en": "Habakkuk" }, "testament": "VT" },
    { "abbrev": { "pt": "sf", "en": "sf" }, "author": "Sofonias", "chapters": 3, "group": "Profetas Menores", "name": { "pt-BR": "Sofonias", "en": "Zephaniah" }, "testament": "VT" },
    { "abbrev": { "pt": "ag", "en": "ag" }, "author": "Ageu", "chapters": 2, "group": "Profetas Menores", "name": { "pt-BR": "Ageu", "en": "Haggai" }, "testament": "VT" },
    { "abbrev": { "pt": "zc", "en": "zc" }, "author": "Zacarias", "chapters": 14, "group": "Profetas Menores", "name": { "pt-BR": "Zacarias", "en": "Zechariah" }, "testament": "VT" },
    { "abbrev": { "pt": "ml", "en": "ml" }, "author": "Malaquias", "chapters": 4, "group": "Profetas Menores", "name": { "pt-BR": "Malaquias", "en": "Malachi" }, "testament": "VT" },
    { "abbrev": { "pt": "mt", "en": "mt" }, "author": "Mateus", "chapters": 28, "group": "Evangelhos", "name": { "pt-BR": "Mateus", "en": "Matthew" }, "testament": "NT" },
    { "abbrev": { "pt": "mc", "en": "mc" }, "author": "Marcos", "chapters": 16, "group": "Evangelhos", "name": { "pt-BR": "Marcos", "en": "Mark" }, "testament": "NT" },
    { "abbrev": { "pt": "lc", "en": "lc" }, "author": "Lucas", "chapters": 24, "group": "Evangelhos", "name": { "pt-BR": "Lucas", "en": "Luke" }, "testament": "NT" },
    { "abbrev": { "pt": "jo", "en": "jo" }, "author": "João", "chapters": 21, "group": "Evangelhos", "name": { "pt-BR": "João", "en": "John" }, "testament": "NT" },
    { "abbrev": { "pt": "atos", "en": "atos" }, "author": "Lucas", "chapters": 28, "group": "Histórico", "name": { "pt-BR": "Atos", "en": "Acts" }, "testament": "NT" },
    { "abbrev": { "pt": "rm", "en": "rm" }, "author": "Paulo", "chapters": 16, "group": "Cartas", "name": { "pt-BR": "Romanos", "en": "Romans" }, "testament": "NT" },
    { "abbrev": { "pt": "1co", "en": "1co" }, "author": "Paulo", "chapters": 16, "group": "Cartas", "name": { "pt-BR": "1ª Coríntios", "en": "1 Corinthians" }, "testament": "NT" },
    { "abbrev": { "pt": "2co", "en": "2co" }, "author": "Paulo", "chapters": 13, "group": "Cartas", "name": { "pt-BR": "2ª Coríntios", "en": "2 Corinthians" }, "testament": "NT" },
    { "abbrev": { "pt": "gl", "en": "gl" }, "author": "Paulo", "chapters": 6, "group": "Cartas", "name": { "pt-BR": "Gálatas", "en": "Galatians" }, "testament": "NT" },
    { "abbrev": { "pt": "ef", "en": "ef" }, "author": "Paulo", "chapters": 6, "group": "Cartas", "name": { "pt-BR": "Efésios", "en": "Ephesians" }, "testament": "NT" },
    { "abbrev": { "pt": "fp", "en": "fp" }, "author": "Paulo", "chapters": 4, "group": "Cartas", "name": { "pt-BR": "Filipenses", "en": "Philippians" }, "testament": "NT" },
    { "abbrev": { "pt": "cl", "en": "cl" }, "author": "Paulo", "chapters": 4, "group": "Cartas", "name": { "pt-BR": "Colossenses", "en": "Colossians" }, "testament": "NT" },
    { "abbrev": { "pt": "1ts", "en": "1ts" }, "author": "Paulo", "chapters": 5, "group": "Cartas", "name": { "pt-BR": "1ª Tessalonicenses", "en": "1 Thessalonians" }, "testament": "NT" },
    { "abbrev": { "pt": "2ts", "en": "2ts" }, "author": "Paulo", "chapters": 3, "group": "Cartas", "name": { "pt-BR": "2ª Tessalonicenses", "en": "2 Thessalonians" }, "testament": "NT" },
    { "abbrev": { "pt": "1tm", "en": "1tm" }, "author": "Paulo", "chapters": 6, "group": "Cartas", "name": { "pt-BR": "1ª Timóteo", "en": "1 Timothy" }, "testament": "NT" },
    { "abbrev": { "pt": "2tm", "en": "2tm" }, "author": "Paulo", "chapters": 4, "group": "Cartas", "name": { "pt-BR": "2ª Timóteo", "en": "2 Timothy" }, "testament": "NT" },
    { "abbrev": { "pt": "tt", "en": "tt" }, "author": "Paulo", "chapters": 3, "group": "Cartas", "name": { "pt-BR": "Tito", "en": "Titus" }, "testament": "NT" },
    { "abbrev": { "pt": "fm", "en": "fm" }, "author": "Paulo", "chapters": 1, "group": "Cartas", "name": { "pt-BR": "Filemom", "en": "Philemon" }, "testament": "NT" },
    { "abbrev": { "pt": "hb", "en": "hb" }, "author": "Desconhecido", "chapters": 13, "group": "Cartas", "name": { "pt-BR": "Hebreus", "en": "Hebrews" }, "testament": "NT" },
    { "abbrev": { "pt": "tg", "en": "tg" }, "author": "Tiago", "chapters": 5, "group": "Cartas", "name": { "pt-BR": "Tiago", "en": "James" }, "testament": "NT" },
    { "abbrev": { "pt": "1pe", "en": "1pe" }, "author": "Pedro", "chapters": 5, "group": "Cartas", "name": { "pt-BR": "1ª Pedro", "en": "1 Peter" }, "testament": "NT" },
    { "abbrev": { "pt": "2pe", "en": "2pe" }, "author": "Pedro", "chapters": 3, "group": "Cartas", "name": { "pt-BR": "2ª Pedro", "en": "2 Peter" }, "testament": "NT" },
    { "abbrev": { "pt": "1jo", "en": "1jo" }, "author": "João", "chapters": 5, "group": "Cartas", "name": { "pt-BR": "1ª João", "en": "1 John" }, "testament": "NT" },
    { "abbrev": { "pt": "2jo", "en": "2jo" }, "author": "João", "chapters": 1, "group": "Cartas", "name": { "pt-BR": "2ª João", "en": "2 John" }, "testament": "NT" },
    { "abbrev": { "pt": "3jo", "en": "3jo" }, "author": "João", "chapters": 1, "group": "Cartas", "name": { "pt-BR": "3ª João", "en": "3 John" }, "testament": "NT" },
    { "abbrev": { "pt": "jd", "en": "jd" }, "author": "Judas", "chapters": 1, "group": "Cartas", "name": { "pt-BR": "Judas", "en": "Jude" }, "testament": "NT" },
    { "abbrev": { "pt": "ap", "en": "ap" }, "author": "João", "chapters": 22, "group": "Revelações", "name": { "pt-BR": "Apocalipse", "en": "Revelation" }, "testament": "NT" }
];